language: node_js

node_js:
  - "8"
  - "7"
  - "6"

cache:
  yarn: true

branches:
  only:
  - main
  - develop
  except:
  - gh-pages-src

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install
